"""Generate embedded truecolor mascot lines for welcome_mascot.py."""
from __future__ import annotations

import re
import sys
from pathlib import Path

from PIL import Image

_AGENT_CORE = Path(__file__).resolve().parent.parent

SRC = Path(
    r"C:\Users\21136\.cursor\projects\d-my-agent\assets"
    r"\c__Users_21136_AppData_Roaming_Cursor_User_workspaceStorage_empty-window_images_"
    r"dfba2e76f606de55268dbe9642156580_4737315992841300801-e7a0c301-fe46-431f-ade4-e85d431dbee5.png"
)
WIDTH = 32
HALF = "\u2580"
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def crop_face(im: Image.Image) -> Image.Image:
    w, h = im.size
    return im.crop((int(w * 0.14), int(h * 0.04), int(w * 0.86), int(h * 0.70)))


def truecolor_lines(im: Image.Image, width: int) -> list[str]:
    ar = im.width / im.height
    rows = max(14, int(width / ar * 0.52))
    pix_h = rows * 2
    small = im.resize((width, pix_h), Image.Resampling.LANCZOS)
    px = small.load()
    lines: list[str] = []
    for y in range(0, pix_h, 2):
        parts: list[str] = []
        for x in range(width):
            tr, tg, tb, ta = px[x, y]
            br, bg, bb, ba = px[x, y + 1]
            if ta < 20 and ba < 20:
                parts.append(" ")
                continue
            if ta < 20:
                parts.append(f"\033[48;2;{br};{bg};{bb}m{HALF}\033[0m")
            elif ba < 20:
                parts.append(f"\033[38;2;{tr};{tg};{tb}m{HALF}\033[0m")
            else:
                parts.append(
                    f"\033[38;2;{tr};{tg};{tb}m\033[48;2;{br};{bg};{bb}m{HALF}\033[0m"
                )
        lines.append("".join(parts))
    return lines


def visible_len(line: str) -> int:
    return len(ANSI_RE.sub("", line))


def main() -> None:
    if not SRC.is_file():
        raise SystemExit(f"missing source image: {SRC}")
    lines = truecolor_lines(crop_face(Image.open(SRC).convert("RGBA")), WIDTH)
    print(f"rows={len(lines)} width={max(visible_len(x) for x in lines)}")
    out = _AGENT_CORE / "welcome_mascot_data.py"
    body = [
        "# Generated by scripts/gen_welcome_mascot_data.py — re-run to refresh.",
        "from __future__ import annotations",
        "",
        f"SPRITE_WIDTH = {WIDTH}",
        'SPRITE_LABEL = "打工仔"',
        "TRUECOLOR_LINES: tuple[str, ...] = (",
    ]
    for line in lines:
        body.append(f"    {line!r},")
    body.append(")")
    body.append("")
    out.write_text("\n".join(body), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
