# {{project_name}}

Monorepo scaffold: `backend/` (Spring Boot) + `frontend/` (Vue 3 + Vite).

## Quick start

```bash
cd backend && mvn spring-boot:run
cd frontend && npm install && npm run dev
```

Generated by `scaffold_project` recipe `spring-vue`.
